version: "3"

services:
  postgresql:
    image: bitnami/postgresql:14.9.0
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: secret
      POSTGRESQL_USERNAME: mattermost
      POSTGRESQL_PASSWORD: secret
      POSTGRESQL_DATABASE: mmuser

  openldap:
    image: docker.io/bitnami/openldap:2.6
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USERS=user1,user2
      - LDAP_PASSWORDS=password1,password2
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap/var/lib/ldap:/var/lib/ldap
      - ./ldap/etc/ldap/slapd.d:/etc/ldap/slapd.d

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
    ports:
      - "8080:8080"
    depends_on:
      - openldap

  mattermost:
    image: mattermost/mattermost-enterprise-edition:9.2.0-rc1
    environment:
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://mattermost:secret@postgresql:5432/mattermost?sslmode=disable&connect_timeout=10
    ports:
      - "8065:8065"
    depends_on:
      - postgresql
    volumes:
      - ./mattermost/config.json:/mm/mattermost/config/config.json
