version: "3"

services:
  postgresql:
    image: bitnami/postgresql:14.9.0
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: secret
      POSTGRESQL_USERNAME: mattermost
      POSTGRESQL_PASSWORD: secret
      POSTGRESQL_DATABASE: mmuser

  openldap:
    image: docker.io/bitnami/openldap:2.6
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USERS=user1,user2
      - LDAP_PASSWORDS=password1,password2
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap/var/lib/ldap:/var/lib/ldap
      - ./ldap/etc/ldap/slapd.d:/etc/ldap/slapd.d

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
    ports:
      - "8080:8080"
    depends_on:
      - openldap

  gitlab:
    image: gitlab/gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - conf_files/gitlab.rb:/etc/gitlab/gitlab.rb
      - data:/var/opt/gitlab

volumes:
  config:

