version: "3"

services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=secret1,secret2
    volumes:
      - openldap-data:/bitnami/openldap

  postgresql:
    image: bitnami/postgresql:14.9.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=secret
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_PASSWORD=secret
      - POSTGRESQL_DATABASE=keycloak
    volumes:
      - postgresql-data:/bitnami/postgresql

  keycloak:
    image: bitnami/keycloak:22.0.5
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
      KEYCLOAK_DATABASE_HOST: postgresql
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: secret
      KEYCLOAK_CREATE_REALMS: polytech
      KEYCLOAK_DEFAULT_REALM: polytech
      KEYCLOAK_EXTRA_ARGS: "-Dkeycloak.import=/config"
    volumes:
      - ./keycloak/realm.json:/config/realm.json
    depends_on:
      - postgresql
      - openldap

  gitlab:
    image: gitlab/gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = {
          'main' => {
            'label' => 'LDAP',
            'host' =>  'openldap',
            'port' => 1389,
            'uid' => 'sAMAccountName',
            'bind_dn' => 'OU=users,DC=domain,DC=org',
            'encryption' => 'plain',
            'verify_certificates' => false,
            'timeout' => 10,
            'active_directory' => false,
            'base' => 'dc=example,dc=org',
            'lowercase_usernames' => 'false',
            'retry_empty_result_with_codes' => [80],
            'allow_username_or_email_login' => true,
            'block_auto_created_users' => false
          }
        }
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - ./gitlab/gitlab.rb:/etc/gitlab/gitlab.rb
      - gitlab-data:/var/opt/gitlab

volumes:
  openldap-data:
  postgresql-data:
  gitlab-data:
