version: "3"

services:
  postgresql:
    image: bitnami/postgresql:14.9.0
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: secret
      POSTGRESQL_USERNAME: mattermost
      POSTGRESQL_PASSWORD: secret
      POSTGRESQL_DATABASE: mmuser

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  mattermost:
    image: mattermost/mattermost-team-edition:5.39.0
    environment:
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://mattermost:secret@postgresql:5432/mattermost?sslmode=disable&connect_timeout=10
    ports:
      - "8065:8065"
    depends_on:
      - postgresql
    volumes:
      - ./mattermost/config.json:/mm/mattermost/config/config.json
